# Generated by Django 4.1.6 on 2023-07-01 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0002_alter_user_trade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit_Balance')),
                ('date', models.DateTimeField(blank=True, verbose_name='Deposit_Balance')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Deposit_Balance')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='Deposit_Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
