# Generated by Django 4.1.6 on 2023-07-01 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0003_deposit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
