# Generated by Django 4.1.6 on 2023-07-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0005_remove_user_total_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Deposit_History',
        ),
    ]
