# Generated by Django 4.1.6 on 2023-07-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0006_investment_plans_delete_deposit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_plans',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='investment_plans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
    ]
