# Generated by Django 4.1.6 on 2023-07-01 23:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0007_alter_investment_plans_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit_Balance')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Deposit_Balance')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='Deposit_Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Investment_Plans',
        ),
    ]
