# Generated by Django 4.1.6 on 2023-07-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0009_alter_deposit_history_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit_history',
            old_name='date',
            new_name='timestamp',
        ),
    ]
