# Generated by Django 4.1.6 on 2023-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0011_withdrawal_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal_history',
            name='address',
        ),
        migrations.AlterField(
            model_name='deposit_history',
            name='method',
            field=models.CharField(default='Bitcoin', max_length=50, verbose_name='Deposit Method'),
        ),
        migrations.AlterField(
            model_name='deposit_history',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Deposit Status'),
        ),
        migrations.AlterField(
            model_name='withdrawal_history',
            name='method',
            field=models.CharField(default='Bitcoin', max_length=50, verbose_name='Deposit Method'),
        ),
        migrations.AlterField(
            model_name='withdrawal_history',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Deposit Status'),
        ),
    ]
