# Generated by Django 4.1.6 on 2023-07-05 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0012_remove_withdrawal_history_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='deposit_balance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit_Balance'),
        ),
    ]
