# Generated by Django 4.1.6 on 2023-07-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0013_user_verify_alter_user_deposit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
    ]
