# Generated by Django 4.1.6 on 2023-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0014_remove_user_refcode_remove_user_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
