# Generated by Django 4.1.6 on 2023-08-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_trade', '0015_user_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
